task_id:"Ey7rthoif8V8YcDRuv54Y"  situation_id:"P3Kt7abKXCklArfXp-wlD"  check_item:{check_item_id:"vo0LJGgqc7pHpmlwyUDxR"  command:{command_id:"pYDLrZ6mQLWY5eNhHUu7a"  command_line:"progate diagnose"}  command:{command_id:"YCCfmRFKEv6JpXYnDJYxf"  command_line:"bash ./.progate/check_puppeteer.sh"}}  check_item:{check_item_id:"x2aFpyjThSoPKcdDNDz3O"  command:{command_id:"4PpTEFwaf0JsBGYzwvW4A"  command_line:"npm run test:style"}}